DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tokens CASCADE;
DROP TABLE IF EXISTS stacks CASCADE;
DROP TABLE IF EXISTS stack_card_quantities CASCADE;
DROP TABLE IF EXISTS decks CASCADE;
DROP TABLE IF EXISTS deck_card_quantities CASCADE;
DROP TABLE IF EXISTS trading_deal CASCADE;
DROP TABLE IF EXISTS cards CASCADE;