DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tokens CASCADE;
DROP TABLE IF EXISTS decks CASCADE;
DROP TABLE IF EXISTS trading_deals CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS packages CASCADE;
DROP TABLE IF EXISTS battles CASCADE;
DROP TABLE IF EXISTS battle_logs CASCADE;
